production:
	adapter: postgresql
	database: <%= ENV['PRODUCTION_DATABASE_NAME'] %>
	host: <%= ENV['PRODUCTION_DATABASE_HOST'] %>

development:
	adapter: postgresql
	database: <%= ENV['DEVELOPMENT_DATABASE_NAME'] %>
	host: <%= ENV['DEVELOPMENT_DATABASE_HOST'] %>

test:
	adapter: postgresql
	database: <%= ENV['TEST_DATABASE_NAME'] %>
	host: <%= ENV['TEST_DATABASE_HOST'] %>