# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41cec89cedb11f4b198e766655a13fcbff32c1a40474b8746228cc183c80df1958b7cd1046eec848cf825cbfd124579403a44631d97554282f5fbfef1b1a3a27

test:
  secret_key_base: 8b89c1e2902133f5c823838d62f5195f7765264fbe9c5019c991add653d9d0bc6b1ad27da678a132a5dce7cb97e6ae0e94ec9b5cd62ce0e687f3de22ce2811fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
